name: Build and Deploy Docs

on:
  push:
    branches:
      - main  # Change to your default branch if different
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install ASDF
      run: |
        sudo apt-get update
        sudo apt-get install -y curl git
        git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.11.3
        echo '. "$HOME/.asdf/asdf.sh"' >> ~/.bashrc
        echo '. "$HOME/.asdf/completions/asdf.bash"' >> ~/.bashrc
        source ~/.bashrc
        asdf plugin add uv
        asdf install uv latest
        asdf global uv latest

    - name: Create virtual environment and install dependencies
      run: |
        uv venv
        .venv/bin/python -m pip install .[docs]

    - name: Build documentation
      run: |
        .venv/bin/python -m sphinx -T -b html -d docs/_build/doctrees -D language=en docs docs/_build/html

    - name: Upload built documentation as artifact
      uses: actions/upload-artifact@v3
      with:
        name: html-docs
        path: docs/_build/html
